"""Initial migration

Revision ID: 9d8c214a21df
Revises: 
Create Date: 2022-03-24 14:19:38.849544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import flask_authorize

# revision identifiers, used by Alembic.
revision = '9d8c214a21df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('allowances', flask_authorize.mixins.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('cookie', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.Column('proxy_host', sa.String(length=255), nullable=True),
    sa.Column('proxy_port', sa.String(length=255), nullable=True),
    sa.Column('proxy_login', sa.String(length=255), nullable=True),
    sa.Column('proxy_pass', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('unmasked_vendor', sa.String(length=255), nullable=True),
    sa.Column('unmasked_renderer', sa.String(length=255), nullable=True),
    sa.Column('resolution', sa.String(length=255), nullable=True),
    sa.Column('last_enter', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('user')
    op.drop_table('roles')
    # ### end Alembic commands ###
